{% set name = "torchmd" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchmd-{{ version }}.tar.gz
  sha256: ccb0402043a396deb760d9a8fa0b3008b863fc3f798519c076b0d602f58a40cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - versioneer
  run:
    - python >=3.6
    - pyyaml
    - scipy
    - pytorch
    - torchvision
    - moleculekit
    - networkx
    - pandas
    - tqdm

test:
  imports:
    - torchmd
    - torchmd.forcefields
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.torchmd.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: End-To-End Molecular Dynamics (MD) Engine using PyTorch
  description: |
    TorchMD intends to provide a simple to use API for performing
    molecular dynamics using PyTorch. This enables researchers to more
    rapidly do research in force-field development as well as integrate
    seamlessly neural network potentials into the dynamics, with the
    simplicity and power of PyTorch.
  doc_url: http://www.torchmd.org/
  dev_url: https://github.com/torchmd/torchmd/

extra:
  recipe-maintainers:
    - jan-janssen
